import js from '@eslint/js';

export default [
    {
        // Ignore generated/vendored content and test fixtures
        ignores: [
            'node_modules/**',
            'audits/**',
            'data/**',
        ],
    },
    {
        ...js.configs.recommended,
        files: ['modules/**/*.js', 'SolverV2.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                // Browser globals used in modules
                requestAnimationFrame: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                Date: 'readonly',
                Math: 'readonly',
                parseInt: 'readonly',
                Map: 'readonly',
                Set: 'readonly',
                Promise: 'readonly',
                Float64Array: 'readonly',
                Uint16Array: 'readonly',
                Uint8Array: 'readonly',
                Int32Array: 'readonly',
                AbortController: 'readonly',
                Object: 'readonly',
                Array: 'readonly',
                JSON: 'readonly',
                Error: 'readonly',
                isNaN: 'readonly',
                isFinite: 'readonly',
                URLSearchParams: 'readonly',
                structuredClone: 'readonly',
                TextEncoder: 'readonly',
                navigator: 'readonly',
                cancelAnimationFrame: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                localStorage: 'readonly',
                fetch: 'readonly',
                queueMicrotask: 'readonly',
                process: 'readonly',
                firebase: 'readonly',
                __initial_auth_token: 'readonly',
                window: 'readonly',
                document: 'readonly',
                HTMLElement: 'readonly',
                SVGElement: 'readonly',
            },
        },
        rules: {
            // Errors: real bugs
            'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
            'no-undef': 'error',
            'no-constant-condition': 'error',
            'no-duplicate-case': 'error',
            'no-self-assign': 'error',
            'no-unreachable': 'error',

            // Disabled: these have valid uses in this codebase
            'no-fallthrough': 'off',      // intentional in switch statements
            'no-prototype-builtins': 'off',
        },
    },
    {
        // Scripts use Node globals and CommonJS-adjacent patterns
        files: ['scripts/**/*.mjs'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                console: 'readonly',
                process: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                Date: 'readonly',
                Math: 'readonly',
                parseInt: 'readonly',
                Map: 'readonly',
                Set: 'readonly',
                Promise: 'readonly',
                Float64Array: 'readonly',
                Uint16Array: 'readonly',
                Uint8Array: 'readonly',
                Int32Array: 'readonly',
                Object: 'readonly',
                Array: 'readonly',
                JSON: 'readonly',
                Error: 'readonly',
                isNaN: 'readonly',
                isFinite: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                Buffer: 'readonly',
                fetch: 'readonly',
                queueMicrotask: 'readonly',
                globalThis: 'readonly',
                window: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
            'no-undef': 'error',
            'no-constant-condition': 'error',
            'no-duplicate-case': 'error',
            'no-self-assign': 'error',
            'no-unreachable': 'error',
            'no-fallthrough': 'off',
            'no-prototype-builtins': 'off',
        },
    },
];
